### ISSUE TITLE
[epic] Migration projet web sous Clever Cloud / passage PHP 7.4

### ISSUE THREAD

**Issue by agallou** [afup/web#1330]
# Tests fonctionnels

- [x] https://github.com/afup/web/issues/1110

# Passage PHP 7.0

- [x] https://github.com/afup/web/issues/905
- [x] https://github.com/afup/web/issues/1331
- [x] #1374
- [x] https://github.com/afup/web/pull/1423
- [x] Modifier vhost pour passer sur fpm en 7.0
- [x] Modifier crons pour passer en 7.0
- [x] Suivre les erreurs New Relic

# Migration Clever Cloud (en 7.0)

- [x] Vérifier les TTL du domaine afup.org
- [x] Vérifier les TTL du domaine www.planete-php.fr
- [x] Changer DNS www.planete-php.fr sur Gandi
- [x] #1415
- [x] #1416
- [x] https://github.com/afup/web/issues/1422
- [x] #1455
- [x] https://github.com/afup/web/issues/1442
- [x] https://github.com/afup/web/pull/1483
- [x] https://github.com/afup/web/issues/1480
- [x] https://github.com/afup/web/pull/1533
- [x] https://github.com/afup/web/pull/1531 
- [x] https://github.com/afup/web/pull/1532
- [x] https://github.com/afup/web/pull/1522
- [x] Vérifier le fuseau horaire utilisé (Géré coté applicatif ici : sources/Afup/Bootstrap/_Common.php)
- [x] https://github.com/afup/web/pull/1534
- [x] Vérifier que le upload_max_filesize permette d'uploader les PDFs du dossier de sponsoring (il est à upload_max_filesize => 32M` donc c'est bon)
- [x] Vérifier utilité du fichier JSON
    - https://github.com/afup/deploy/blob/master/vars/static.yml#L14C12-L14C32
    - Servait pour les mailings lists, n'est plus utile depuis https://github.com/afup/web/pull/1359
- [x] Vérifier comment on migre les dossiers statiques (cf https://github.com/afup/deploy/blob/master/vars/static.yml)
- [x] https://github.com/afup/web/pull/1542
- [x] Mise en place instance préprod
  - [x] Configuration htdocs/docs en fsbucket
  - [x] Configuration htdocs/uploads en fsbucket
- [x] Mettre en place page de migration via vhost
- [x] Mettre en place nouveau système de backup
- [x] Préparer PR pour ajouter "Hébergé sur Clever Cloud" dans le footer comme sur le baromètre
- [x] Faire recette pole outils
- [x] Préparer document de migration
- [x] Définir date de migration
- [x] Mise en place instance prod
  - [x] Créer application php
  - [x] Bien ajouter authentification temporaire en htpasswd
  - [x] Configuration htdocs/docs en fsbucket
  - [x] Configuration htdocs/uploads en fsbucket
  - [x] Faire une passe sur toutes les variables d'environnement
  - [x] Configurer DNS

# Passage PHP 7.4
- [x] https://github.com/afup/web/issues/1332
- [x] https://github.com/afup/web/issues/1333
- [x] https://github.com/afup/web/issues/1437
- [x] Changer variable d'environnement en préprod
- [x] Changer variable d'environnement en prod
- [x] Suivre les erreurs sur New Relic

**Comment by agallou** [comment]
Après la migration sur Clever Cloud le 27 novembre, on vient il y a 10 minutes de passer en 7.4 en prod.
