### ISSUE TITLE
Afup.org: Sitemap

### ISSUE THREAD

**Issue by xavierleune** [afup/web#386]
Il faut mettre en oeuvre un sitemap pour le site afup.org et le déclarer dans google search console

**Comment by Korbeil** [comment]
Hello !

Concernant le sitemap j'aimerais faire un point sur son contenu dans un premier temps (et les divisions de celui-ci), voilà ce que je propose:
- `sitemap.xml` (faisant références au différents "sous"-sitemaps)
- `sitemap-site.xml` (Contenant tout le contenu lié à l'associations et aux antennes, les menus: "Actualités" / "Association" / "Antennes" / "Vidéos")
- `sitemap-event.xml` (Le contenu lié aux Events PHP à venir et passés)
- `sitemap-barometre.xml` (Contenu du rapport du barometre courant et passés)

Je ne prends pas en compte "Planete PHP" vu qu'il est sur un nom de domaine différent et qu'il lui faudra donc un sitemap à part.

Concernant le détail du contenu nous pourrons revoir ça lors de la PR, mais dans l'ensemble ça vous parait ok ?

**Comment by agallou** [comment]
pour sitemap-event.xml il risque d'être plus compliqué à générer si on veux le faire de la même façon que sitemap-site.xml vu que c'est un wordpress (qui doit avoir ses propres plugins pour gérer le sitemap).

est-ce que tu sais si avoir 3 sitemap pour event.afup.org, afup.org et barometre.afup.org changerait beaucoup de choses ?

Pour le contenu, notamment sur sitemap-site.xml, oui, c'est exactement ça.
Est-ce que tu a besoin d'un coup main pour la partie seed pour qu'on génère des données de test sur ces parties ?

**Comment by Korbeil** [comment]
Du coup ça rejoins #634 concernant event, il doit me manquer quelque chose pour le faire fonctionner.
Sinon pour WordPress il doit exister des plugins qui gère le sitemap et ensuite il suffira de le référencer dans le sitemap principal.

Changerais dans quel sens ? Au niveau SEO ? non, c'est la même chose qu'un include, il va juste chercher les fichiers où tu lui dis.

Plus sur le site event qui est pas fonctionnel de mon côté ! Je vais voir pour faire des seeds demain (j'ai un peu de train, ça m'occupera)

**Comment by Korbeil** [comment]
# Todo
- [x] Mettre en place une lib pour la gestion du sitemap
- [x] Pages statiques dans le sitemap
- [x] Talks dans le sitemap
- [ ] News dans le sitemap

**Comment by stakovicz** [comment]
Je viens d'ajouter les pages des membres.
